name: CI

on:
  push:
  pull_request:

defaults:
  run:
    working-directory: packages/telo-node

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
          cache-dependency-path: packages/telo-node/yarn.lock

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Format check
        run: yarn format:check

      - name: Typecheck
        run: yarn typecheck

      - name: Build
        run: yarn build